FROM apecloud/kingbase:v008r006c009b0014-unit
COPY entry.sh /home/kingbase/entry.sh
#ENTRYPOINT [ "sh", "-l", "/home/kingbase/entry.sh" ]
ENTRYPOINT ["/home/kingbase/cluster/bin/docker-entrypoint.sh"]